Initialize project with components
Rhaegar121/React-BookStore pull request #1
Opened 2023-02-21 17:23 UTC by Rhaegar121

In this PR, I have completed the following tasks.

1. Setup linters for react
2. Used correct gitflow
3. Added two routers: `/books` and `/categories`
4. Created `Navbar` component
5. Created `Book` component
6. Created `Form` component

2023-02-21 18:08 UTC, mckent05 requested changes
Hi @Rhaegar121, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You have setup your components correctly and your app renders properly 👏 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 18:08 UTC, mckent05 commented on src/App.js
> +}
- Good job done so far, I suggest having this component in another js file, so as to make your code as modular as possible 👍 👍 
- I also advise using arrow functions in order to maintain `ES6` syntax as it is the more accepted syntax in use globally. Please fix this 👍 👍

2023-02-21 18:08 UTC, mckent05 commented on src/App.js
>  }
- I advise using arrow functions in order to maintain ES6 syntax as it is the more accepted syntax in use globally. Please fix this 👍 👍

2023-02-21 18:08 UTC, mckent05 commented on src/compoents/Book.js
> +/* eslint-disable react/prop-types */
- Please remove all disabled linter checks, remember that linters help us write code that is clean and easy to maintain. Please fix this 🙏

2023-02-22 08:57 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Rhaegar121, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Git Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 08:57 UTC, Qoosim commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [OPTIONAL] This link is not broken. Kindly follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to properly set it up for your project.

![license](https://user-images.githubusercontent.com/26597432/220569532-6f4c9f8d-fdc1-45fd-bd4a-10f8280bbcdb.png)

2023-02-22 09:11 UTC, merged